# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ansa-offsite"
client_id = "531d5ac13bcc98942dc59a3eae55baf6"
application_url = "https://discusses-gathering-level-spirituality.trycloudflare.com"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_payment_gateways,write_payment_sessions"

[auth]
redirect_urls = [
  "https://discusses-gathering-level-spirituality.trycloudflare.com/auth/callback",
  "https://discusses-gathering-level-spirituality.trycloudflare.com/auth/shopify/callback",
  "https://discusses-gathering-level-spirituality.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-a9a799dd.myshopify.com"
automatically_update_urls_on_dev = true
